"""new fields in user model

Revision ID: 32668f63d445
Revises: 3cd5f4505f60
Create Date: 2018-10-06 20:00:57.512812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32668f63d445'
down_revision = '3cd5f4505f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('about_me', sa.String(length=255), nullable=True))
    op.add_column('player', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'last_seen')
    op.drop_column('player', 'about_me')
    # ### end Alembic commands ###
