"""Initial DB

Revision ID: 3cd5f4505f60
Revises: 
Create Date: 2018-10-02 20:36:31.981024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd5f4505f60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_email'), 'player', ['email'], unique=True)
    op.create_index(op.f('ix_player_first_name'), 'player', ['first_name'], unique=False)
    op.create_index(op.f('ix_player_last_name'), 'player', ['last_name'], unique=False)
    op.create_index(op.f('ix_player_username'), 'player', ['username'], unique=True)
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_played', sa.Date(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('winner_skill', sa.SmallInteger(), nullable=True),
    sa.Column('winner_must_win', sa.SmallInteger(), nullable=True),
    sa.Column('winner_points_won', sa.SmallInteger(), nullable=True),
    sa.Column('loser_id', sa.Integer(), nullable=True),
    sa.Column('loser_skill', sa.SmallInteger(), nullable=True),
    sa.Column('loser_must_win', sa.SmallInteger(), nullable=True),
    sa.Column('loser_points_won', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['loser_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('loser_id', sa.Integer(), nullable=True),
    sa.Column('innings', sa.SmallInteger(), nullable=True),
    sa.Column('eight_on_break', sa.Boolean(), nullable=True),
    sa.Column('winner_table_run', sa.Boolean(), nullable=True),
    sa.Column('winner_ball_in_hands', sa.SmallInteger(), nullable=True),
    sa.Column('loser_ball_in_hands', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['loser_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('match')
    op.drop_index(op.f('ix_player_username'), table_name='player')
    op.drop_index(op.f('ix_player_last_name'), table_name='player')
    op.drop_index(op.f('ix_player_first_name'), table_name='player')
    op.drop_index(op.f('ix_player_email'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
